version: "3.7"
services:
    www01:
        build: 
            context: .
            dockerfile: '.docker/Dockerfile'
            args: 
                ENVIRONMENT: development
                XDEBUG_ENABLE: 'true'
        container_name: project_name_www01
        env_file: '.env'
        image: project_name
        links:
            - db
        ports:
            - "8000:80"
            - "8001:443"
        volumes:
            - .:/var/www/html
    db:
        container_name: project_name_db
        env_file: '.env'
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3306:3306'
        restart: always
        volumes:
            - .docker/mysql/storage:/var/lib/mysql:cached
    adminer:
        image: adminer
        ports:
            - "8080:8080"
        restart: always
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
            - "8025:8025"
        restart: always
