version: "3.7"
services:
    www01:
        build:
            target: development
        container_name: project_name_www01_dev
        image: project_name:development
        restart: unless-stopped
        volumes:
            - .:/var/www/html
            - "var/www/html/vendor"
    db:
        container_name: project_name_db_dev
        restart: unless-stopped
    adminer:
        container_name: project_name_adminer_dev
        image: adminer:4.7.7
        ports:
            - "8080:8080"
        restart: unless-stopped
    mailhog:
        container_name: project_name_mailhog_dev
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
            - "8025:8025"
        restart: unless-stopped
