version: "3.7"
services:
    www01:
        build:
            context: .
            dockerfile: ".docker/dev.Dockerfile"
            target: development
        container_name: project_name_www01
        env_file: ".env"
        image: project_name:development
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
            - 'var/www/html/vendor'
    # www01_production:
    #     build:
    #         context: .
    #         dockerfile: ".docker/prod.Dockerfile"
    #         target: production
    #     container_name: project_name_www01
    #     env_file: ".env"
    #     image: project_name:production
    #     ports:
    #         - "80:80"
    #         - "443:443"
    #     volumes:
    #         - .:/var/www/html
    db:
        container_name: project_name_db
        env_file: ".env"
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - .docker/db/storage:/var/lib/mysql:cached
    adminer:
        image: adminer:4.7.4
        ports:
            - "8080:8080"
        restart: always
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
            - "8025:8025"
        restart: always
