version: "3.7"
services:
    www01:
        build:
            context: "./php"
            dockerfile: ".docker/Dockerfile"
        env_file: "php/.env"
        ports:
            - "80:80"
            - "443:443"

    db:
        command: --default-authentication-plugin=mysql_native_password
        env_file: "php/.env"
        image: mysql:8.0
        ports:
            - "3306:3306"
        volumes:
            - .docker/db/storage:/var/lib/mysql:cached
